### ISSUE TITLE
Seems not to work with Phonegap Build on iOS

### ISSUE THREAD

**Issue by RedEars** [filfat-Studios-AB/cordova-plugin-spinnerdialog#4]
I added this plugin to my Phonegap Build config file but it seems to not work properly for iOS.
Build seems to work but when I download the app from PGB it can't be installed on the device. 
Also in the installed Plugins Tab in PGB there is no installed version of this plugin. In the Log file everything looks ok. 

Anyone having the same issues?

**Comment by filfat** [comment]
Hi, we have yet to add this plugin to PGB, I'll look into this as soon as possible thus enabling your app to properly function :)

**Comment by RedEars** [comment]
I'm sorry - my fault!! I was so stupid to select the wrong certificate...Plugin works great with PGB!
